export const browserCoreExamples = [
  "opin browser status",
  "opin browser start",
  "opin browser stop",
  "opin browser tabs",
  "opin browser open https://example.com",
  "opin browser focus abcd1234",
  "opin browser close abcd1234",
  "opin browser screenshot",
  "opin browser screenshot --full-page",
  "opin browser screenshot --ref 12",
  "opin browser snapshot",
  "opin browser snapshot --format aria --limit 200",
  "opin browser snapshot --efficient",
  "opin browser snapshot --labels",
];

export const browserActionExamples = [
  "opin browser navigate https://example.com",
  "opin browser resize 1280 720",
  "opin browser click 12 --double",
  'opin browser type 23 "hello" --submit',
  "opin browser press Enter",
  "opin browser hover 44",
  "opin browser drag 10 11",
  "opin browser select 9 OptionA OptionB",
  "opin browser upload /tmp/file.pdf",
  'opin browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "opin browser dialog --accept",
  'opin browser wait --text "Done"',
  "opin browser evaluate --fn '(el) => el.textContent' --ref 7",
  "opin browser console --level error",
  "opin browser pdf",
];
